version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i
      - echo "✅ Packages installed successfully."
  pre_build:
    commands: 
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
  build:
    commands:
      npm start
      - echo "✅ Build passed successfully."
 